# Makefile for Alcetronics M68K board drivers

obj-$(CONFIG_MCP3208_ADC) += mcp3208.o

obj-$(CONFIG_ETH_ALCE) += alce_eth.o
obj-$(CONFIG_MMC_ALCE) += alce_mmc.o

obj-$(CONFIG_SERIAL_FT245_ALCE) += alce_ft245.o
obj-$(CONFIG_SERIAL_FPGA_ALCE) += alce_uart.o

# experimental / testing / off-board devices

obj-$(CONFIG_MAS3507D_ALCE) += alce_mas3507d.o
obj-$(CONFIG_MAX31855_ALCE) += max31855.o
